dashboard/urls.py
from django.urls import path

from . import views

app_name = 'dashboard'

urlpatterns = [
    # /dashboard/
    path('', views.index, name='index'),

    # /dashboard/login
    path('login', views.logIn, name='log_in'),

    #/dashboard/logout
    path('logout', views.logOut, name='log_out'),

    #ajax calls
    path('get_all_users', views.get_all_users, name='get_all_users'),
    path('fire_coordinates', views.fire_coordinates_for_ajax, name='fire_coordinates_for_ajax')

]

sj_dashboard/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('dashboard/', include('dashboard.urls')),
    path('admin/', admin.site.urls),
]

dashboard/models.py
from django.db import models

# Create your models here.
class Users(models.Model):
    type_of_respondant = models.CharField(max_length=30)
    name = models.CharField(max_length=30)
    #last_name = models.CharField(max_length=30)
    email = models.CharField(max_length=100)
    firebase_id = models.CharField(max_length=100)
    latitude = models.FloatField(default=0)
    longitude = models.FloatField(default=0)
    highlight = models.BooleanField(default=False)
    heart_rate = models.IntegerField(default=0)
    carbon_monoxide_level = models.IntegerField(default=0)
    sorrounding_temperature = models.IntegerField(default=0)
    unique_id = models.AutoField(primary_key=True)
    def __str__(self):
        return self.name

dashboard/forms.py
from django import forms
from django.forms import ModelForm
from .models import Users

class LoginForm(forms.ModelForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'placehoder':'username'}))
    email = forms.CharField(widget=forms.TextInput(attrs={'placeholder':'Email Address'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder':'Password'}))
    class Meta:
        model = Users
        fields = ['username', 'email', 'password']
        

dashboard/views.py
from django.shortcuts import render, redirect
import plotly.plotly as py
import pandas as pd
import plotly.graph_objs as go
from plotly.offline import download_plotlyjs, init_notebook_mode, plot, iplot
from .forms import LoginForm
import pyrebase
import geopy.distance as geo_d
from .models import Users
import numpy as np
from django.http import JsonResponse

#These are urls for other pages on the website
INDEX_URL = "/dashboard/"
LOGIN_URL = "/dashboard/login"

config = {
    'apiKey': "AIzaSyCmpmXBztg8rRdUINXA08sRe3tEcCdaBVU",
    'authDomain': "smokejumper-6adc2.firebaseapp.com",
    'databaseURL': "https://smokejumper-6adc2.firebaseio.com",
    'projectId': "smokejumper-6adc2",
    'storageBucket': "smokejumper-6adc2.appspot.com",
    'messagingSenderId': "650905800259"
}

#firebase.initializeApp(config)
firebase = pyrebase.initialize_app(config)

# Get a reference to the database service
db = firebase.database()

# global user variable
current_user = ""

first_respondant_list = list()
fire_dict = dict()
all_respondant_types = list()

#colors
resp_colors = {
    'firefighters':'rgb(200,100,0)',
    'medic':'rgb(76,117,230)'
}
resp_colors_hightlighted = {
    'firefighters':'rgb(255,165,0)',
    'medic':'rgb(255,100,0)'
}
#######TEST########
# data to save
# data = {
#     "name": "Mortimer 'Morty' Smith"
# }
# Pass the user's idToken to the push method
#results = db.child("users").push(data, user['idToken'])

def checkSession(request):
    template = "login.html"
    print("\tChecking session")
    current_user = request.session.get('current_user', '')
    print(current_user)
    if (not current_user):
        print("\tCurrent user not registered")
        return False
    return True

def logIn(request):
    print("\tlogin function--------------")
    login_form = LoginForm
    template = "login.html"
    context = dict()
    current_user = request.session.get('current_user', '')
    context['current_user'] = current_user
    if(not current_user):
        print("\tcurrent_user not logged in")
        if request.method == 'GET':
            print("\tGet method")
            context['form'] = login_form(None)
            return render(request, template, context)
        else:
            print("\tPost")
            print("\tPassword is: ", request.POST.get('password'))
            context['form'] = login_form(request.POST),
            form = login_form(request.POST)
            print(form)
            #check if the form was filled correctly then proceed

            #don't know y this isn't working
            #if form.is_valid():
            print("\tFFFFFFFFFFform is valid")
            email = request.POST.get('email')
            password = request.POST.get('password')
            # Get a reference to the auth service
            auth = firebase.auth()
            # Log the user in
            user = auth.sign_in_with_email_and_password(email, password)
            if(not user):
                print("\tLogin didn't work.")
                return redirect(LOGIN_URL)
            else:
                request.session['current_user'] = user
                print("\tsending to index")
                return redirect(INDEX_URL)
    else:
        context = {
            'current_user':current_user
        }
        return render(request,template,context)

    return render(request, template, context)

#logout of a session
def logOut(request):
    print("\tlogging out")
    if(request.session['current_user']):
        del request.session['current_user']
    return redirect(LOGIN_URL)

# Create your views here.
def index(request):
    print("\tin index -------------------------")
    if(not checkSession(request)):
        return redirect(LOGIN_URL)
    # TODO: lattitude, longitude to be changed with center of coordinates acquired from get_fire_position()
    initialize_first_respondants_from_firebase()

    not_highlighted_users = Users.objects.filter(highlight=False)
    highlighted_users = Users.objects.filter(highlight=True)
    fire_lat_long = get_location_points_for_fire()

    p = draw_mapbpx_map(not_highlighted_users, highlighted_users, fire_lat_long)

    context = {
        'map' : str(p)
    }

    print("I at home")
    return render(request, "map_section.html", context)

#this method returns a plot object for the plotly mapbox
def draw_mapbpx_map(not_highlighted_users, highlighted_users, fire_lat_long):
    global resp_colors, resp_colors_hightlighted
    data = list()
    for respondant_type in all_respondant_types:
        temp = not_highlighted_users.filter(type_of_respondant = respondant_type)
        r_color = resp_colors[respondant_type]
        size = 20
        data = make_data_block_for_scattermapbox(data, temp, r_color, size)

    if highlighted_users.exists():
        for respondant_type in all_respondant_types:
            temp = highlighted_users.filter(type_of_respondant = respondant_type)
            r_color = resp_colors_hightlighted[respondant_type]
            size = 22
            data = make_data_block_for_scattermapbox(data, temp, r_color, size)

    fire_area_source = get_fire_area_pollygon_dict(fire_lat_long)
    fill_fire_area = {
        "id": "park-boundary",
        "type": "fill",
        "source": fire_area_source,
        "paint": {
            "fill-color": "#E63E2C",
            "fill-opacity": 0.4
        },
        "filter": ["==", "$type", "Polygon"]
    }

    layers=[
        dict(
            sourcetype = 'geojson',
            source =fire_area_source,
            color='rgb(0,0,230)',
            type = 'line',
            line=dict(width=1.5),
       ),
       dict(
            sourcetype = 'geojson',
            source = fire_area_source,
            type='fill',
            opacity = 0.4,
            color = "#888888"
       )

     ]

    latitude = 37.3382
    longitude = -121.8863
    zoom_var = 14

    layout = go.Layout(
        autosize=True,
        hovermode='closest',
        mapbox=dict(
            accesstoken='pk.eyJ1IjoiYWtzaGF0NDYiLCJhIjoiY2ptbnY5N2RnMHh4MzNwbnkyaDQ0Nmx6dCJ9.O1wq_YvpFSvvxUsun8-_EQ',
            layers=layers,
            style='mapbox://styles/akshat46/cjp7tz1tx3uxv2sqzu8eko8wz',
            bearing=0,
            center=dict(
                lat=latitude,
                lon=longitude
            ),
            pitch=0,
            zoom=zoom_var
        )
    )

    fig = dict(data=data, layout=layout)
    return plot(fig, include_plotlyjs=False, output_type='div',  config={'displayModeBar': False,'showLink': False})

#This method gives the blueprint or the map of where to draw the fire pollygon
def get_fire_area_pollygon_dict(lat_long):
    #coordinates = [lon, lat] -> this is the format
    i = 0
    lat_lon_len = len(lat_long[0])
    coord = []
    temp = []
    while i < lat_lon_len:
        temp = [lat_long[1][i], lat_long[0][i]]
        coord.append(temp)
        i = i + 1

    temp = [lat_long[1][0], lat_long[0][0]]
    coord.append(temp)

    fire_polly_dict = {
        "type": "FeatureCollection",
        "features": [{
            "type": "Feature",
            "geometry": {
                "type": "Polygon",
                "coordinates": [
                    coord
                ]
            }
        }]
    }
    return fire_polly_dict

def initialize_first_respondants_from_firebase():
    global db, all_respondant_types
    db_instance = db.get()

    #get the values from the database instance
    all_the_tables = db_instance.val()

    #get each of the nodes of the database on firebase from the returned object above
    # This is the outermost layer of the table
    table_keys = list(all_the_tables.keys())
    all_respondant_types = table_keys[1:]
    #skip the first element of the list
    for type_of_object in table_keys[1:]:
        #Go through each of the main tables other than the first one
        ind_object_table = all_the_tables[type_of_object] #is a touple
        #iterate through the dict and get the latlong from the dictionary objects

        #Keys for the inner sub layer, like the firefighter objects or the medic objects in the data
        ind_object_table_keys = list(ind_object_table.keys())
        for ind_object_key in ind_object_table_keys:
            #These are the keys for the attributes of the individual objects
            object_attr_keys = list(ind_object_table[ind_object_key].keys())
            fireb_id = ind_object_key
            #local_object = make_object_locally(type_of_object, field_keys_of_object, ind_object)
            c_level = ind_object_table[ind_object_key][object_attr_keys[0]]
            h_rate = ind_object_table[ind_object_key][object_attr_keys[1]]
            lat_long = ind_object_table[ind_object_key][object_attr_keys[2]].split(',')
            n = ind_object_table[ind_object_key][object_attr_keys[3]]
            s_temp = ind_object_table[ind_object_key][object_attr_keys[4]]
            obj, create = Users.objects.get_or_create(firebase_id=fireb_id)
            if create:
                print("-> Had to create this one", n)
            obj.name = n
            obj.latitude = float(lat_long[0])
            obj.longitude = float(lat_long[1])
            obj.type_of_respondant = type_of_object
            obj.heart_rate = h_rate
            obj.carbon_monoxide_level = c_level
            obj.sorrounding_temperature = s_temp
            obj.save()
            print("---------------->", obj.type_of_respondant)
            print(obj.name)

    return

def get_location_of_respondants(respondants):
    lat = list(respondants.values_list('latitude', flat=True))
    lon = list(respondants.values_list('longitude', flat=True))
    lat = pd.Series(lat)
    lon = pd.Series(lon)
    #combine them together to return the lat lon array
    lat_long = []
    lat_long.append(lat)
    lat_long.append(lon)
    return lat_long

#This method gets the location points for the fire from firebase
def get_location_points_for_fire():
    global fire_dict, db
    data_ref = db.get()

dashboard/templates/base.html
<!DOCTYPE html>

<html>
<head>
	<meta charset=utf-8 />
	<title>Modest Maps JS Demo | Spotlight</title>
</head>
{% load static %}
{% load sass_tags %}
<link href='https://api.tiles.mapbox.com/mapbox-gl-js/v0.51.0/mapbox-gl.css' rel='stylesheet' />
<link rel="stylesheet" type="text/css" href="{% static 'css/accordion.min.css' %}">
<link href="{% sass_src 'css/map.scss' %}" rel="stylesheet" type="text/css" />
<link href="{% sass_src 'css/main.scss' %}" rel="stylesheet" type="text/css" />
<link href="{% sass_src 'css/navbar.scss' %}" rel="stylesheet" type="text/css" />
<link href="{% sass_src 'css/sidebar.scss' %}" rel="stylesheet" type="text/css" />
<link href="{% sass_src 'css/login.scss' %}" rel="stylesheet" type="text/css" />
<link href="https://fonts.googleapis.com/css?family=Oswald:700" rel="stylesheet">
<link href='https://fonts.googleapis.com/css?family=Rubik:300,400,500,700' rel='stylesheet' type='text/css'>
<body>
	{% include 'navmenu.html' %}
	{% include 'sidebar.html' %}
	<div id="map"></div>
	<div class="banner-wrapper">
	<div class="distance-banner">
		<div class="banner-title">Distance Mode</div>
		<div class='distance-container'>Total Distance: <div id='distance'>...</div>km</div>
	</div>
	<div class="controls-wrapper">
		<div id="control"><i class ="icon" data-feather="x"></i></div>
		<div id="control"><i class ="icon" data-feather="trash-2"></i></div>
	</div>
</div>
</body>
<script src='https://api.mapbox.com/mapbox.js/plugins/turf/v2.0.2/turf.min.js'></script>
<script src='https://api.tiles.mapbox.com/mapbox-gl-js/v0.51.0/mapbox-gl.js'></script>
<script src='https://rawgithub.com/stamen/modestmaps-js/master/modestmaps.min.js'></script>
<script src='https://code.jquery.com/jquery-3.3.1.min.js'></script>
<script src='https://cdn.jsdelivr.net/npm/feather-icons/dist/feather.min.js'></script>
<script src="{% static "js/map.js" %}"></script>
<script src="{% static "js/getUsers.js" %}"></script>
<script src="{% static "js/accordion.min.js" %}"></script>
<script src="{% static "js/sidebar.js" %}"></script>
<script src="{% static "js/navbar.js" %}"></script>
<script>
feather.replace()
</script>
</html>

dashboard/templates/login.html
{% load sass_tags %}
{% load static %}


<link href="{% sass_src 'css/login.scss' %}" rel="stylesheet" type="text/css" />
<link href="https://fonts.googleapis.com/css?family=Oswald:700" rel="stylesheet">
<link href='https://fonts.googleapis.com/css?family=Rubik:500' rel='stylesheet' type='text/css'>

<div class="main-page-wrapper">
	<div id="smokejumper-title">SmokeJumper</div>
  {% if not current_user %}
    <form action="{% url 'dashboard:log_in' %}" method="post">
      {% csrf_token %}
      <label><input class="form-element" type="text" placeholder="Email" name="email"></label>
      <label><input class="form-element" type="password" placeholder="Password" name="password"></label>
      <input class="login-logout" type="submit" value="SIGN IN">
    </form>
  {% else %}
    <a class="login-logout" href="{% url 'dashboard:log_out' %}">LOG OUT</a>
  {% endif %}
</div>

dashboard/templates/map.html
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
    <script>
      function clearContainer() {
        var element = document.getElementById('container');
        while (element.firstChild) {
          element.removeChild(element.firstChild);
        }
      }

      function showMap() {
        console.log('MAP shown');
        clearContainer();
        var element = document.createElement('div');
        var textnode = document.createTextNode('MAP');
        element.appendChild(textnode);
        document.getElementById('container').appendChild(element);
      }

      function toggleMenu() {
        document.getElementById('sidebar').classList.toggle('active');
      }
    </script>
    <style>
      #sidebar {
        position: fixed;
        width: 200px;
        height: 100%;
        background: #042902;
        left: -200px;
        transition: all 500ms linear;
      }

      #sidebar.active {
        left: 0px;
      }

      #sidebar ul li {
        list-style: none;
      }

      #sidebar ul a {
        color: yellow;
        padding: 15px 10px;
        border-bottom: 1px solid rgba(100, 100, 100, 0.3);
        text-align: center;
        text-decoration: none;
        display: inline-block;
        font-family: sans-serif;
      }

      #sidebar ul a:focus {
        color: lightgreen;
      }

      #sidebar .toggle-btn {
        position: absolute;
        left: 230px;
        top: 20px;
      }

      #sidebar .toggle-btn span {
        display: block;
        width: 30px;
        height: 5px;
        background: #151719;
        margin: 5px 0px;
      }

      #container {
        position: absolute;
        left: 300px;
      }

      .icons {
        right: 10px;
      }

    </style>
  </head>
  <body>
    <div id="sidebar">
      <div class="toggle-btn" onclick="toggleMenu()">
        <span></span> <span></span> <span></span>
      </div>
      <ul>
        <li><a href="#" onclick="showMap()"><span class="glyphicon glyphicon-map-marker icons"></span>MAP</a></li>
        <li><a href="#"><span class="glyphicon glyphicon-fire icons"></span>FIREFIGHTERS</a></li>
        <li><a href="#"><span class="glyphicon glyphicon-user icons"></span>ACCOUNT</a></li>
        <li></img><a href="#"><span class="glyphicon glyphicon-cog icons"></span>SETTINGS</a></li>
      </ul>
      <div id="container"></div>
    </div>
  </body>
</html>

dashboard/templates/map_section.html
{% extends "base.html" %}

{% block map %}
{% csrf_token %}

{% load sass_tags %}
<link href="{% sass_src 'css/map.scss' %}" rel="stylesheet" type="text/css" />

<script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
<div id='map'>
	{{ map|safe }}
</div>
{% endblock %}

dashboard/templates/navmenu.html
{% load sass_tags %}
{% load static %}

<div id="navbar" class="sidenav">
	 <div class="close-button" onclick="closeNav()"><i data-feather="minus"></i></div>
	 <div class="nav-element"><i class ="icon" data-feather="map"></i> Map</div>
	 <div class="nav-element"><i class ="icon" data-feather="users"></i> Firefighters</div>
	 <div class="nav-element"><i class ="icon" data-feather="user"></i> Account</div>
	 <a href = 'login' class="nav-element"><i class ="icon" data-feather="settings"></i> Settings</a>
	 <div class="open-button" onclick="openNav()"><i class ="icon" data-feather="menu"></i></div>
</div>

dashboard/templates/rightmenu.html
{% load sass_tags %}
{% load static %}

<link href="{% sass_src 'css/rightmenu.scss' %}" rel="stylesheet" type="text/css" />
<meta name="viewport" content="width=device-width, initial-scale=1">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="{% static "js/rightmenu.js" %}"></script>

<div id="main">
    <div id="sidebar">
        <div class="toggle-btn" onclick="toggleMenu()">
            <span></span> <span></span> <span></span>
        </div>
        <ul>
            <li><a href="#"><span class="glyphicon glyphicon-fire icons"></span>FIREFIGHTERS</a></li>
            <li><a href="#"><span class="glyphicon glyphicon-user icons"></span>ACCOUNT</a></li>
            <li></img><a href="#"><span class="glyphicon glyphicon-cog icons"></span>SETTINGS</a></li>
        </ul>
    </div>
</div>

dashboard/templates/sidebar.html
{% load sass_tags %}
{% load static %}

<div class="rightbar hover-on">
	<div class="sidebar-close-button" onclick="closeBar()"><i data-feather="minus"></i></div>
	<div class="fillerelement"></div>

	<div class="sidebar-element-wrapper ">
		<div class="sidebar-element" id="get-all-highlight">
			<div class="ui accordion">
				<div class="label title">
					<i class ="icon" data-feather="target"></i> Highlight
				</div>
				<div class="content">

				</div>
			</div>
		</div>
		<div class="sidebar-element" id="calculate-distance">
			<div class="ui accordion">
				<div class="label title">
					<i class ="icon" data-feather="navigation"></i> Find Distance
				</div>
				<div class="content">
					Click on two markers.
				</div>
			</div>
		</div>
		<div class="sidebar-element" id="get-all-detail">
			<div class="ui accordion">
				<div class="label title">
					<i class ="icon" data-feather="info"></i> Details
				</div>
				<div class="content">

				</div>
			</div>
		</div>
	</div>

	<div class="open-button" onclick="openBar()"><i class ="icon" data-feather="activity"></i> Activity</div>
</div>